### ISSUE TITLE
Can't get the content expiration

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#79] opened 2015-08-14 15:26 UTC
1. create an official template in ADFS/on-premise, set the content expiration, set view permission for User A.
2. Use this template to encrypt a PDF file.
3. Use A can't get the content expiration date.

here is our code to get the content expiration date
![ctime](https://cloud.githubusercontent.com/assets/10860444/9276903/5145933c-42d9-11e5-9ba0-99a0c447fb4a.png)

PS: 
1. In Windows, user A can get the correct content expiration date

**Comment by AgentRX** [comment] 2015-08-26 15:50
@Kammy6679 , could you provide us PFILE with VIEW permissions to john.smith@msopentechtest01.onmicrosoft.com?

**Comment by Kammy6679** [comment] 2015-08-27 01:42
@AgentRX , This issue can be produced in ADFS/on-premise, not Azure AD RMS. And I don't have the permission to create a template of view permission in Azure AD RMS with john.smith@msopentechtest01.onmicrosoft.com.

**Comment by prvijay** [comment] 2015-09-10 05:46
@Kammy6679 - as indicated earlier, please set up an on-prem RMS infrastructure to repro the issue and share the details. The one shared by Josh was for testing purposes and should not be taken as a long term infrastructure solution. Help us with the required info to make progress on this issue.

**Comment by Kammy6679** [comment] 2015-09-11 05:01
@AgentRX , @prvijay , I will send a on-prem RMS infrastructure to you by email.

**Comment by Kammy6679** [comment] 2015-09-11 06:04
@AgentRX ,
1. I have created an official template(<b>tester01_View_Per</b>) in ADFS/on-premise, set the content expiration, set view permission for tester01@mobile.dev.foxitsoftware.cn.
2. Use mingjian_chen@msopentechtest01.onmicrosoft.com to get the template of tester01_View_Per, and encrypt a PDF file. And then send this protected file to tester01@mobile.dev.foxitsoftware.cn.
3. using tester01@mobile.dev.foxitsoftware.cn, we can open this protected file, but can't get the content expiration date.

**Comment by prvijay** [comment] 2015-09-11 16:24
@Kammy6679 - what is the scenario impact here? If this is seen only for on-prem ADFS, it may not even be in the scope of the original agreement. This was not flagged as a release blocker, so we are going to wait on this issue while @AgentRX switches his focus on other things.

**Comment by AgentRX** [comment] 2015-09-11 16:31
@Kammy6679, please give credentials for all users and connections in this scenario. I couldn't reproduce it using only your description.

**Comment by Kammy6679** [comment] 2015-09-14 10:09
@AgentRX , @prvijay ,
Here is a video for reproducing this issue.
http://sync-us.foxitsoftware.com/pm/rms/temp/#79.wmv

PS: This is not a serious problem. Just can't show the content expiration time in the Foxit Reader.

**Comment by prvijay** [comment] 2015-09-14 14:43
@Kammy6679 - Ok, then let's not gate your release on this issue.

@Kammy6679 - share the latest build, @AgentRX - can you repro the issue before tonight's meeting. Let's see if it's some low hanging fix.

**Comment by AgentRX** [comment] 2015-09-14 15:02
@Kammy6679, prease provide video file with access.
When I try to get the video I get "Forbidden" error.

**Comment by Kammy6679** [comment] 2015-09-14 15:43
@AgentRX , here is a new link for video: http://sync-us.foxitsoftware.com/pm/rms/temp/79.wmv

**Comment by prvijay** [comment] 2015-09-14 21:21
Even in the Windows platform, the Content Expiration Date shows up as  Unknown. Is there anything specific to the Linux SDK here? http://1drv.ms/1iKay3T

**Comment by prvijay** [comment] 2015-09-15 16:34
@Kammy6679 - in the video it's not clear if the content expiry is being set for the file. Either way, it seems to be a small interpretation of the if-check which can be handled by the application. Closing the issue - reactivate if there is a business need to address it in the SDK.

**Comment by prvijay** [comment] 2016-05-12 17:11
Reactivating the issue as Foxit is still facing this

**Comment by raeitan** [comment] 2016-05-19 00:14
Tried reproducing the issue, and failed to do it. 
Please use wire shark (or similar) to capture the communication between the server and your macine and share with us. 
Or preferably set up a remote environment where we can test new binaries with the fix.  
1. One scenario where this can happen is if the Content Expiry time is above the year 2037, Linux have some accuracy issues with that. 
2. If the Linux Machines clock is different than the Windows machine and the content is no longer viable.

**Closed as completed** 2016-05-23 16:17 UTC

**Comment by Kammy6679** [comment] 2016-05-27 10:06
@raeitan 

right now, only this case can reproduce this issue:
（1）. Use this account(rms@mobile.dev.foxitsoftware.cn) and this template(test01_view) to encrypt a PDF file to PPDF file.

(2). Use this account(tester01@mobile.dev.foxitsoftware.cn) to decrypt this PPDF, then can't get the content expiration date.

I will send you the account information and the test file.
