### ISSUE TITLE
Inconsistent offline and caching policies across SDKs

### ISSUE THREAD

**Issue by joshgav** [AzureAD/rms-sdk-for-cpp#5] opened 2015-06-22 18:26 UTC
from @Kammy6679
1. Although we set `PolicyDescriptor::OfflineCacheLifetimeInDays(int value)` when protecting the files, we always get `0` as the value when unprotecting the files.
2. No matter what `PolicyDescriptor::ContentValidUntil` is set to at protection-time, no value is returned at unprotection-time.
   #### Protection code
   
   ```
   if (m_bContentExpir)
        {
            m_contentExpirDateTime = m_contentExpirDateTime.toUTC();
            time_t c_time = m_contentExpirDateTime.toTime_t();
            auto endValidation = chrono::system_clock::from_time_t(c_time);
            policyDescriptor->ContentValidUntil(endValidation);
        }
   ```
   ### Unprotection code:
   
   ```
   bool CMSDataInteractionLinux::GetContentValidUntil(QString &qsUntil)
   {
       if(NULL == m_pUserPolicy)
           return false;
   
       std::chrono::time_point<std::chrono::system_clock> until_time =
               m_pUserPolicy->ContentValidUntil();
   
       time_t until_time_t = system_clock::to_time_t(until_time);
       std::tm* until_tm = gmtime(&until_time_t);
   
       char cTimeTemp[25] = {0};
       std::sprintf(cTimeTemp, "%04d/%02d/%02d %02d:%02d:00",
                    until_tm->tm_year,
                    until_tm->tm_mon,
                    until_tm->tm_mday,
                    until_tm->tm_hour,
                    until_tm->tm_min);
       std::string csTime(cTimeTemp);
   
       qsUntil = QString::fromStdString(csTime);
       return true;
   }
   ```

**Comment by joshgav** [comment] 2015-06-22 18:27
@munjaldoshi thoughts?

**Comment by munjaldoshi** [comment] 2015-06-22 20:40
We should completely remove the option OfflineCacheLifetimeInDays. We plan to remove the ability for an app or the user to set this value.

**Comment by gurgenh** [comment] 2015-06-24 17:13
OfflineCacheLifetimeInDays should be replaced by a boolean (OfflineAccess). The app should set whether caching is allowed or not, but it shouldn't specify or make any assumptions about the longevity of the cache.

**Comment by munjaldoshi** [comment] 2015-06-24 22:54
Gurgen is right. I forgot to mention we need a boolean. Just a nit suggestion: use the name allowOfflineAccess for the boolean for consistency with other platforms.

**Comment by AgentRX** [comment] 2015-06-25 14:44
I've removed OfflineCacheLifetimeInDays  and added **allowOfflineAccess** boolean to REST UsageRestrictionsResponse and PublishCustomRequest objects (with serialize/deserialize it).
API references to OfflineCacheLifetimeInDays were changed to AllowOfflineAccess
Cache control now also checks if AllowOfflineAccess to cache responses.

Here is PR: https://github.com/AzureAD/rms-sdk-for-cpp/pull/17

@munjaldoshi, does allowOfflineAccess variable work now or you are just going to implement it in future?

**Comment by joshgav** [comment] 2015-06-25 14:53
@AgentRX, can you also tackle #13 with this work?

**Comment by AgentRX** [comment] 2015-06-25 15:12
@joshgav, yes

**Comment by joshgav** [comment] 2015-06-30 17:41
Thanks to @AgentRX's help, here's a summary of the current usability of each of the following properties. Serialization of requests and responses is all in the one [jsonserializer.cpp](https://github.com/AzureAD/rms-sdk-for-cpp/blob/master/sdk/rms_sdk/Json/jsonserializer.cpp) file.

@vladimp Can you confirm this is the expected behavior from the service side?

**ContentValidUntil** - If set in request is _not_ reflected in response. This SDK does _not_ set ContentValidUntil in request.

**LicenseValidUntil** - If set in request _is_ reflected in response. This SDK _does_ set LicenseValidUntil in request.

**AllowOfflineAccess** - If set in request is not (yet) reflected in response. This SDK _does_ set AllowOfflineAccess in request. This property is incubating.

**OfflineCacheLifetimeInDays** - If set in request is not reflected in response. This SDK does not offer this setting. This property is deprecated.

**Comment by vladimp** [comment] 2015-07-01 00:08
Hi Josh!

What you defined is not accurate,  (the names on the service are a little bit confusing..)

When creating a custom policy(publishing scenario) from the policy descriptor the following properties can be passed:

Request:

```
{
  "PreferDeprecatedAlgorithms": boolean,
  "AllowAuditedExtraction": boolean,
  "ReferralInfo": string,
  "SignedApplicationData": {
    "key": "value",
    …
  },
  "Policy": {
  "Descriptors": [ {
    "Name": string,
    "Description": string,
    "Language": string
   }],
    "UserRights": [{
      "Users": array of string,
      "Rights": array of string }...],

    "UserRoles": [{
      "Users": array of string,
      "Roles": array of string }...],

    "IntervalTimeInDays": int,
    "LicenseValidUntil": Time,

    "EncryptedApplicationData": {
      "key": "value",
      …
    }
  }
```

Response:

```
{
  "SerializedPublishingLicense": string,
  "Id": string,
  "Name": string,
  "Description": string,
  "Referrer": string,
  "Owner": string,

  "Key": {
    "Value": string,
    "Algorithm": string,
    "CipherMode": string
  }
}
```

When consuming the serializedLicence :
Request:

```
{
  "SerializedPublishingLicense": string
}
```

Response:

```
{
  "AccessStatus": string,
  "ContentId": string,
  "Id": string,
  "Name": string,
  "Description": string,
  "Referrer": string,
  "Owner": string,
  "ContentValidUntil": Time
  "LicenseValidUntil": Time

  "Key": {
    "Value": string,
    "Algorithm": string,
    "CipherMode": string
  },
  "Rights":[ string array ],
  "Roles":[ string array ],
  "FromTemplate": Boolean,
  "SignedApplicationData": {
    "key": "value",
    …
  },
  "EncryptedApplicationData": {
    "key": "value",
    …
  },
  "IssuedTo": string,

  "Policy": {
    "AllowAuditedExtraction": boolean,

    "UserRights": [{
      "Users": array of string,
      "Rights": array of string }...],

    "UserRoles": [{
      "Users": array of string,
      "Roles": array of string }...],

    "IntervalTimeInDays": int,
    "LicenseValidUntil": Time
  }
}
```
- The Policy object will be returned only to the owner otherwise will be null.
- The ContentValidUntil and LicenseValidUntil outside the Policy object will be always visible.

And this is the confusing part, the values that you set in publishing are set as following on consumption:
- IntervalTimeInDays --> LicenseValidUntil
- LicenseValidUntil --> ContentValidUntil (this is exposed as a property on the userPolicy directly)

In The SDK exposing in the public API:
- contentValiduntil  --> LicenseValidUntil (mapped to this one when creating the REST call)
- offlineCacheLifetimeInDays (should be replaced with allowOfflineAccess) --> IntervalTimeInDays (mapped to this one when creating the REST call in both cases, when exposing it as a bool, 0 for false and send nothing when true)
- Policy.IntervalTimeInDays
  Defines the intervaltime in days.
  If not present then license can be cached forever.
  0: Cannot cache the use license
  +ve number: Use license can only be cached for specified number of days. Client has to contact the server for re-acquiring the use license.

It is also shown in [this document](https://microsoft.sharepoint.com/teams/RMCST/Specstore/RM%20Client/MSIPC-thin/REST%20Service/RTM/IPCv3%20REST%20Service.docx?web=1).
Hopefully now it is more clear…

Thanks,
Vladi

**Comment by AgentRX** [comment] 2015-07-02 16:25
Support IntervalTimeInDays added
DateTime conversion error fixed
AllowOfflineAccess support added

Now all is working correctly

**Comment by joshgav** [comment] 2015-07-08 21:43
Here are the transitions following @AgentRX's PR. I believe we may need to update this to cause the PolicyDescriptor::AllowOfflineAccess property to propagate to the JSON payload as IntervalTimeInDays rather than as AllowOfflineAccess, as per the **[*]**.

Once done, we can treat ContentValidUntil as the legacy expiration date. If it's used in the original publication it's the authoritative date on consumption. If however AllowOfflineAccess is used in publication, then it will become the authoritative info on consumption. The pseudocode below ensures this I believe.

#### Request

| PolicyDescriptor | UserPolicy | PublishCustomRequest | JsonSerializer |
| --- | --- | --- | --- |
| ContentValidUntil | ftContentValidUntil | ftLicenseValidUntil | LicenseValidUntil |
| AllowOfflineAccess | bAllowOfflineAccess | bAllowOfflineAccess[*] | AllowOfflineAccess[*] |
| ? | ? | ? | IntervalTimeInDays |

#### Response

| JsonSerializer | UsageRestrictionsResponse | UserPolicy (private) | UserPolicy |
| --- | --- | --- | --- |
| ContentValidUntil | ftContentValidUntil | m_ftValidityTimeUntil | ContentValidUntil |
| LicenseValidUntil | ftLicenseValidUntil | bAllowOfflineAccess[**] | AllowOfflineAccess |

[*] Should AllowOfflineAccess be converted to IntervalTimeInDays for the JSON payload? If so, it seems the value should be time::max so that it will always translate to AllowOfflineAccess(true) on consumption, even a long time later.

[**] Here's the logic in pseudocode:

```
m_ftValidityTimeUntil = ftContentValidUntil
if m_ftValidityTimeUntil != ftLicenseValidUntil
    if ftLicenseValidUntil > now
        bAllowOfflineAccess = true
    else
        bAllowOfflineAccess = false
```

**Comment by AgentRX** [comment] 2015-07-13 13:19
Hello @joshgav,

There are two important things of custom policy:
1. JSON 'Policy' is only owner view section. It's haven't been set in response for other users
2. There is no support for AllowOfflineAccess boolean yet

Below is the updated table:

#### Request

| PolicyDescriptor | UserPolicy | PublishCustomRequest | JsonSerializer |
| --- | --- | --- | --- |
| ContentValidUntil | ftContentValidUntil | ftLicenseValidUntil | Policy.LicenseValidUntil |
| AllowOfflineAccess | bAllowOfflineAccess | bAllowOfflineAccess | Policy.AllowOfflineAccess and Policy.IntervalTimeInDays |

#### Response

| JsonSerializer | UsageRestrictionsResponse | UserPolicy (private) | UserPolicy |
| --- | --- | --- | --- |
| ContentValidUntil and Policy.LicenseValidUntil | ftContentValidUntil | m_ftValidityTimeUntil | ContentValidUntil |
| LicenseValidUntil and Policy.IntervalTimeInDays | ftLicenseValidUntil | bAllowOfflineAccess | AllowOfflineAccess |

[*] Below is the updated logic in pseudocode:

```
ftValidityTimeUntil = ftContentValidUntil
bAllowOfflineAccess = true;

if(Policy.IntervalTimeInDays <= 0)
   bAllowOfflineAccess = false;

if m_ftValidityTimeUntil != ftLicenseValidUntil && ftLicenseValidUntil < now
   bAllowOfflineAccess = false
```

#### **Examples:**

**Request**
PolicyDescriptor.ContentValidUntil = 2015-07-15T15:14:50;
PolicyDescriptor.AllowOfflineAccess = false;

{"Policy":{"IntervalTimeInDays":0,"LicenseValidUntil":"2015-07-15T15:14:50", allowOfflineAccess":false}}

**Response**
{"ContentValidUntil":"2015-07-15T15:14:00","LicenseValidUntil":"2015-07-13T12:18:50Z",Policy":{"IntervalTimeInDays":0,"LicenseValidUntil":"2015-07-15T15:14:00"}}

**Request**
PolicyDescriptor.ContentValidUntil = 2015-07-15T15:28:13;
PolicyDescriptor.AllowOfflineAccess = true;

{"Policy":{"IntervalTimeInDays":1,"LicenseValidUntil":"2015-07-15T15:28:13","allowOfflineAccess":true}}

**Response**
{"ContentValidUntil":"2015-07-15T15:28:00","LicenseValidUntil":"2015-07-14T12:30:13Z", "Policy":{"IntervalTimeInDays":1,"LicenseValidUntil":"2015-07-15T15:28:00"}}

**Comment by AgentRX** [comment] 2015-07-13 13:23
I've created new merged PR https://github.com/AzureAD/rms-sdk-for-cpp/pull/45

**Comment by joshgav** [comment] 2015-07-14 21:27
@gurgenh please review

**Comment by joshgav** [comment] 2015-07-14 22:36
Thanks @AgentRX. In the last Response above, should it be 2015-07-1**6**? I.e.:

```
{"ContentValidUntil":"2015-07-15T15:28:00","LicenseValidUntil":"2015-07-16T12:30:13Z", "Policy":{"IntervalTimeInDays":1,"LicenseValidUntil":"2015-07-15T15:28:00"}}
```

What would happen if this response was received on 7/25? Would it be marked as AllowOfflineAccess=false? If so, should we set IntervalTimeInDays to int::max so that LicenseValidUntil is always > now?

I believe that `AllowOfflineAccess` will never be a property in the JSON payload, only in the client library. I've asked @gurgenh to clarify.

**Comment by AgentRX** [comment] 2015-07-15 15:55
@joshgav, if I set intervalTimeInDays to int::max Azure Server returns the error:

> {"Code":"Microsoft.RightsManagement.Exceptions.UnexpectedServerException","Message":"Oops. Something went wrong."}

So I've set it to 25 years (about 9125 days). Now it works.

Also there is another thing Azure Server does:
IF Now + Request.intervalTimeInDays > Request.ContentValidUntil THEN Response.intervalTimeInDays = Request.ContentValidUntil - now

### Example

PolicyDescriptor.ContentValidUntil = Now + 100 days;
PolicyDescriptor.AllowOfflineAccess = true;

**Request:**

> {"Policy":"IntervalTimeInDays":9125,"LicenseValidUntil":"2015-10-24T18:49:17", "allowOfflineAccess":true}}

**Response:**

> {"ContentValidUntil":"2015-10-24T18:49:00","LicenseValidUntil":"2015-10-24T18:49:00","Policy":{"IntervalTimeInDays":101,"LicenseValidUntil":"2015-10-24T18:49:00"}}

**Comment by AgentRX** [comment] 2015-07-15 16:01
I've created new PR https://github.com/AzureAD/rms-sdk-for-cpp/pull/48

**Comment by AgentRX** [comment] 2015-07-16 09:01
As we spoke with @vladimp IntervalTimeInDays is set to 30 days when AllowOfflineAccess
New PR: https://github.com/AzureAD/rms-sdk-for-cpp/pull/50

**Comment by vladimp** [comment] 2015-07-16 15:47
Please remove the AllowOfflineAccess from the UserPolicy public surface.
I confirmed that the value for intervalTimeInDays should be set to 30 when AllowOfflineAccess set to True and 0 when set to False.

**Comment by AgentRX** [comment] 2015-07-16 16:53
Hello @vladimp,

```
bool AllowOfflineAccess();
```

Is read-only property of UserPolicy. It refers to private ProtectionPolicy object and not allowed to be changed.

Should I remove it for reading?

**Comment by vladimp** [comment] 2015-07-16 18:19
Yes, We currently not exposing it in other SDK's: iOS, Mac and Android.

**Comment by Kammy6679** [comment] 2015-07-20 02:15
Using RMS SDK for Mac, we can set PolicyDescriptor::OfflineCacheLifetimeInDays(int value) when protecting the files. We cannot get the value when unprotecting the files in Mac OS. This is a bug in RMS SDK for Mac. But we can get the value when unprotecting the files in Windows. This means that the setting is right in RMS SDK for Mac.
For unity and compatibility in each RMS SDK, please  add this feature.

**Comment by joshgav** [comment] 2015-07-20 15:18
Thanks Kammy - as we discussed in this thread, `OfflineCacheLifetimeInDays` is a deprecated property and will eventually be removed from other SDKs as well. Please use `ContentValidUntil` instead.

It would be great if you could describe scenarios you'd like to address and the properties and behaviors you'd like to provide. The service team (@vladimp) can take that into consideration for further planning.

Thanks!

**Comment by Kammy6679** [comment] 2015-07-21 02:49
OfflineCacheLifetimeInDays and ContentValidUntil are the different methods. Please refer to MSICP in the following page and screenshot: https://msdn.microsoft.com/en-us/library/windows/desktop/hh535287(v=vs.85).aspx

![rms](https://cloud.githubusercontent.com/assets/10860444/8791929/e65e9904-2f93-11e5-9860-a2f2b564796e.png)

Please don't remove this method from any SDK. we have some customers who use this feature in Office/Windows.

**Comment by Kammy6679** [comment] 2015-07-21 10:38
we find that:
1. IntervalTimeInDays is set to 30 days by default when AllowOfflineAccess. We cannot chanage this setting.
2.  We set the ContentValidUntil, and the time is 8 hours ahead. We guess it is because the time is not UTC format.
3. We can get the value of ContentValidUntil , but the value is wrong.

**Comment by joshgav** [comment] 2015-07-21 23:00
Hi @Kammy6679,
1. IntervalTimeInDays is by design set to 30 days when AllowOfflineAccess is set to `true`.
2. Please share debug logs following the instructions in the README showing the incorrect time.
3. Where are you getting this value and what is it?

/cc @munjaldoshi @gurgenh @vladimp @prvijay - Cache and content expiration times and how they are handled may need more synchronization across the API and all SDKs. The discrepancies make these hard to rely on currently.

**Comment by vladimp** [comment] 2015-07-21 23:13
IntervalTimeInDays is an internal attribute that controls the cache time to support offline scenario.
On the public surface we expose only the AllowOfflineAccess flag, we make the decision for the developer for how long we cache as this logic is not something the developer should be aware of. This value also depends on server configurations and other features.(such as revocation)

Let me know if you have any other issues or concerns.

**Comment by Kammy6679** [comment] 2015-07-22 10:29
1. In the RMS server, you can create a policy template, which can set OfflineCacheLifetimeInDays
   ![qq 20150727110121](https://cloud.githubusercontent.com/assets/10860444/8897870/de1f5656-344e-11e5-86f1-bcca5407a455.png)

In Foxit Reader, we also provide a same feature ------ create a customized policy template,  which can set OfflineCacheLifetimeInDays. 
1. We cannot provide log. Following are the steps to reproduce the issue:
   a. The content expiration time we set is local system time: 2015-7-24 00:00:00
   b. Change this time to UTC: 2015-7-23 16:00:00
   c. Set ContentValidUntil as the time we get in step b.
   d. In Windows, the content expiration time got by MSICP is 2015-7-24 8:00:00, which is not correct. The right value is 2015-7-24 00:00:00.
2. We use the follow code to get this value. If set the value is 2015-7-24 00:00:00, get the value is 0115-6-23 16:00:00(Is not a fixed value, it may change at any time)

bool CMSDataInteractionLinux::GetContentValidUntil(QString &qsUntil)
{
    if(NULL == m_pUserPolicy)
        return false;

```
std::chrono::time_point<std::chrono::system_clock> until_time =
        m_pUserPolicy->ContentValidUntil();

time_t until_time_t = system_clock::to_time_t(until_time);
std::tm* until_tm = gmtime(&until_time_t);

char cTimeTemp[25] = {0};
std::sprintf(cTimeTemp, "%04d/%02d/%02d %02d:%02d:00",
             until_tm->tm_year,
             until_tm->tm_mon,
             until_tm->tm_mday,
             until_tm->tm_hour,
             until_tm->tm_min);
std::string csTime(cTimeTemp);

qsUntil = QString::fromStdString(csTime);
return true;
```

}

**Comment by Kammy6679** [comment] 2015-07-27 03:24
any update?

**Comment by munjaldoshi** [comment] 2015-08-03 23:29
Kemmy, as mentioned several times in the thread abov,e we want to deprecate the ability for the apps to set cache lifetime in days across all SDKs. Yes, an admin can set it on the server side but that is all we are going to allow going forward. We are going to deprecate that across all platforms in the upcoming months.

The main reason for doing tis that we do not think there is any good reason an app or a user has to worry about how long licenses live in the cache. We want to be able to change our caching characteristics without impacting the applications and the users.

So I suggest you remove the UI option from the current Foxit application to set the exact lifetime in days. You can replace it with a checkbox if you like (we do that in our own applications).

**Comment by Kammy6679** [comment] 2015-08-04 08:07
@munjaldoshi , OK, we will remove the setting of license expiration. Do you have any update about the above 2, 3 
![123333](https://cloud.githubusercontent.com/assets/10860444/9056054/b51b22d8-3ac2-11e5-9110-af8c9bd60013.png)

**Comment by AgentRX** [comment] 2015-08-10 12:29
@Kammy6679, I've fixed ContentValidUntil wrong value on library side

**Comment by AgentRX** [comment] 2015-08-10 12:36
@vladimp, There is some bug on JSON RESP API:

**Request (publishinglicenses):**

{"Policy":{"IntervalTimeInDays":0,"LicenseValidUntil":"**2015-08-12T12:06:29Z**"}}

**BUT Azure Server Response (enduserlicenses):**
{"ContentValidUntil":"**2015-08-12T12:06:00**","LicenseValidUntil":"2015-08-10T12:08:11Z", Policy":{"LicenseValidUntil":"**2015-08-12T12:06:00**"}}

So the response errors:
- seconds are ignored
- Response format in Local time (without 'Z' at end) but MUST be in UTC

**Comment by Kammy6679** [comment] 2015-08-14 08:17
Thank you. This issue has been fixed.

**Closed as completed** 2015-08-14 08:38 UTC
Labels: question
