### ISSUE TITLE
Cannot make API calls in background thread

### ISSUE THREAD

**Issue by joshgav** [AzureAD/rms-sdk-for-cpp#16] opened 2015-06-24 17:11 UTC
From @Kammy6679 

We create a QThread thread to get the service's list of templates, calling `TemplateDescriptor::GetTemplateList` to get the template in `QThread::run`.  After login dialog is shown, we get the following error message:

![image](https://cloud.githubusercontent.com/assets/4421720/8009820/2bfe8cf6-0b60-11e5-8398-3661dcb665b1.png)

Because it will take a long time to get template, we need to get it in a background thread. If this method is wrong, would you please let us know how to get it?

Here is our code about AuthCallback::GetToken  (the same as the rms_sample):

```
AuthenticationContext authContext(ap->Authority(),  AuthorityValidationType::False,  FileCachePtr);
auto result = authContext.acquireToken(
      ap->Resource(),
      ap->UserId(),
      redirect,
      PromptBehavior::Auto);
```

No matter what value of PromptBehavior is set, the above error message will appear.

The async code which gets the template list is:

```
bool CMSDataInteractionLinux::InitTemplateWithUserID(QString &userID)
{
    std::string csUserID = userID.toStdString();
    addCertificates();
    m_officialTempltes = TemplateDescriptor::GetTemplateList(csUserID, m_authenticationCallback);
    return true;
}
```

this function will be called in QThread  run().

**Comment by joshgav** [comment] 2015-06-24 17:13
@v-vlshch Do we provide an `AuthenticationContext::acquireTokenSilent()` method in the rmsauth library? Such a method would not use IWebUI to get a token, but would attempt to use a cached access token or call the /token endpoint with a refresh token only. It would throw an exception if a login dialog is required, such as if the refresh token is expired.

If we do or can provide such a method, that can be used in the AuthenticationCallback for background calls, guaranteeing no need to access the UI.

**Comment by vladimir-shcherbakov** [comment] 2015-06-24 18:03
We don't have  AuthenticationContext::acquireTokenSilent() method in the rmsauth library.

**Comment by joshgav** [comment] 2015-06-24 20:17
@v-vlshch, would you agree that as it stands now `acquireToken` will always need to be invoked on a UI thread, thus making it impossible to run a method making an API call on a background thread? Are there situations where acquireToken relies on cached tokens and doesn't invoke IWebUI?

How hard would it be to add `AuthenticationContext::acquireTokenSilent()`, which would attempt to use a cached access token, or request a new access token using a refresh token, but throw a well-known exception if interactive logon is required?

**Comment by vladimir-shcherbakov** [comment] 2015-06-25 00:58
It's not quite clear what you mean by background thread.
Actually rmsauth invokes  IWebUI only if there is no cached data or the data can't be used to refresh a token,

**Comment by AgentRX** [comment] 2015-06-30 09:30
Hello @Kammy6679,
Here is an example of using QThread to get Templates list:

**declaration:**

```
class TestThread : public QThread {
  Q_OBJECT

public:

  TestThread(rmscore::modernapi::IAuthenticationCallback& auth, QString& userID)
    : m_authenticationCallback(auth), m_userID(userID) {}

protected:

  void run() {
    InitTemplateWithUserID();
  }

  bool InitTemplateWithUserID()
  {
    std::string csUserID = m_userID.toStdString();

    // addCertificates();
    m_officialTempltes = rmscore::modernapi::TemplateDescriptor::GetTemplateList(
      csUserID,
      m_authenticationCallback);
    return true;
  }

public:
  std::vector<rmscore::modernapi::TemplateDescriptor> m_officialTempltes;
  rmscore::modernapi::IAuthenticationCallback& m_authenticationCallback;
  QString m_userID;
};
```

**using:**

```
  auto qtUserId = QString::fromStdString(userId);
  auto wth = new TestThread(auth, qtUserId);

  wth->start();
  wth->wait();
  auto templates = wth->m_officialTempltes;
```

You can use QThread the same way.

**Comment by joshgav** [comment] 2015-06-30 15:29
Thanks @AgentRX !

**Comment by Kammy6679** [comment] 2015-07-01 07:51
Here is our code：

```
if (NULL == m_pInitTemplateThread)
            m_pInitTemplateThread = new CInitTemplatesWorkerThread(this, accessToken);

        QObject::connect(m_pInitTemplateThread, &CInitTemplatesWorkerThread::finished,
                         this, &CFUIElement::InitAllTemplates);
        m_pInitTemplateThread->start();
```

We can't call `wth->wait();`. This is because it will block the thread.

**Comment by AgentRX** [comment] 2015-07-03 10:42
@Kammy6679,
I've reproduced the example you wrote. It works fine:

```
  auto userId = ui->lineEdit_clientId->text();
  auto userEmail = ui->lineEdit_clientEmail->text();
  auto url = ui->lineEdit_redirectUrl->text();

  if (NULL == m_pInitTemplateThread)
    m_pInitTemplateThread = new TestThread(userId, userEmail, url);

  QObject::connect(m_pInitTemplateThread, &TestThread::finished,
                     this, &MainWindow::on_InitAllTemplates);
  m_pInitTemplateThread->start();

  return;
```

But also  could reproduce the same SIGSEGV error when I put AuthCallback local variable as a thread parameter like this example: 

```
  AuthCallback auth(ui->lineEdit_clientId->text(), ui->lineEdit_redirectUrl->text());
  auto userId = ui->lineEdit_clientEmail->text();

  if (NULL == m_pInitTemplateThread)
    m_pInitTemplateThread = new TestThread(auth, userId);
 ...
 return;
```

It's happened because after return **auth** will be destroyed before is being used.

I think the main problem with **accessToken** variable which is copying as a reference. Please check it.

**Comment by Kammy6679** [comment] 2015-07-06 02:16
Is there a pop-up login window? After login dialog is shown, we can reproduce this issu.

**Comment by AgentRX** [comment] 2015-07-09 16:29
@Kammy6679, what the OS you are testing on?
Have you installed graphical environment? What's the versions of QT Creator?

**Comment by Kammy6679** [comment] 2015-07-10 02:29
QT Creator: 5.3.2
graphical environment:
![222](https://cloud.githubusercontent.com/assets/10860444/8611100/73b6834c-26ee-11e5-9bdf-0e3636e6cadb.png)

**Comment by Kammy6679** [comment] 2015-07-21 07:52
Do you have any update？ 
This issue has affected the process of our app.We hope that this issue can be repaired as soon as possible.

**Comment by joshgav** [comment] 2015-07-21 22:54
Hi @Kammy6679, @AgentRX was not able to reproduce this error and provided a suggestion on what might be wrong with your implementation. Have you tried his suggestion?

**Comment by Kammy6679** [comment] 2015-07-23 01:53
Is there a pop-up login dialog when running your sample? If not, please delete "~/.ms-ad/token_cache.dat", and then try again.

**Comment by Kammy6679** [comment] 2015-07-27 03:24
any update?

**Comment by prvijay** [comment] 2015-08-13 03:29
Johnny, can you bring this up in our next sync up? It seems to be a no-repro from our end and Andrei's sample seems to be working fine.

**Comment by Kammy6679** [comment] 2015-08-13 03:30
Is there a pop-up login window when you are reproducing this issue? If not, I will write a sample to you.

**Comment by AgentRX** [comment] 2015-08-19 10:20
@Kammy6679, I've found the problem.

```
You can't do GUI operations from any thread except the one that created QApplication.
```

So it means if you want to use GUI for authenticate you should get authentication token from main UI thread and then create your back thread OR use SIGNAL/SLOT system to transfer control from back thread to Main UI Thread when it's nessecary to get Auth Token and then return it to the back thread.

**Comment by Kammy6679** [comment] 2015-08-19 11:39
From calling "TemplateDescriptor::GetTemplateList" to "AuthCallback::GetToken" will take 1 ~3 seconds. This mean that Foxit reader takes a long time to get template when clicking the RMS menu every time.

In Mac SDK, we are using "MSTemplateDescriptor templateListWithUserId:userId:authenticationCallback:completionBlock" method to get the template asynchronously.  Can you provide similar methods?

**Comment by AgentRX** [comment] 2015-08-19 15:17
@Kammy6679, According to documentation "The current GNU C library provides the run-time **backward compatibility**"

So it means you can install higher version of GCC:
$ sudo yum install gcc
$ sudo yum update gcc

This will install the latest version of gcc and libraries. Then you can check it by commands:
$ ldd --version
$ /sbin/ldconfig -p | grep stdc++

To deteminate supported versions use command:
strings /usr/lib/libstdc++.so.6 | grep LIBCXX
OR
strings /usr/lib64/libstdc++.so.6 | grep LIBCXX

**Comment by AgentRX** [comment] 2015-08-19 16:35
@Kammy6679, I see. Started to implement this functional

**Comment by prvijay** [comment] 2015-08-20 04:14
Potential fix date is 8/25

**Comment by AgentRX** [comment] 2015-08-24 13:43
@Kammy6679, please check PR: https://github.com/AzureAD/rms-sdk-for-cpp/pull/87

Some notices:
- All UI calls MUST be in main thread. Thats way was added helper function **postToMainThread** which allows to run code in main thread. Also **AuthCallbackUI** and **TemplatesCallbackUI** were added to handle Async requests to UI.
  To handle UI result RMS Sample uses **promise - future** mechanism.
- Now templates list is got async using std::async (of course you can change it to QThread but in that case it's better to use SIGNALS/SLOTS mechanism between QObjects).

If you have some questions **how to** please ask about.

**Comment by Kammy6679** [comment] 2015-08-25 05:56
@AgentRX , using the latest sdk, we find that: you removed "GetTemplateList", add "TemplateDescriptor::GetTemplateListAsync". We hope to continue to keep "GetTemplateList". This is because using "TemplateDescriptor::GetTemplateListAsync" will bring a lot of changes. And how to cancel the operation of the getting template? RMS SDK for Mac provide a method to cancel the operation of the getting template.

**Comment by AgentRX** [comment] 2015-08-25 07:00
@Kammy6679, I removed it to make API interface the same with others ones. To use GetTemplateListAsync in sync mode just call it like this. It's the same as old GetTemplateList call:

auto templates = GetTemplateListAsync(..., std::launch::deferred).get();

There is no mechanism to cancel async operations yet. So I've created the issue: https://github.com/AzureAD/rms-sdk-for-cpp/issues/88

**Comment by Kammy6679** [comment] 2015-08-26 08:31
@AgentRX , Thank you. Please close this issue that has been confirmed fixed.

**Closed as completed** 2015-08-26 09:16 UTC
Labels: help wanted
