### ISSUE TITLE
 Always enter "virtual ConsentList Consents(ConsentList& consents) override;" when decrypting the files

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#76] opened 2015-08-14 05:38 UTC
We don't want to enter "virtual ConsentList Consents(ConsentList& consents) override;"  every time when decrypting the PDF files
1. Use another policy template to encrypt a protected PDF files
2. Always enter "virtual ConsentList Consents(ConsentList& consents) override;" when decrypting the files

In OS X, only decrypting a PDF files(which is encrypted by another RMS server), will  enter "virtual ConsentList Consents(ConsentList& consents) override;". For example: the current is a Online user login, then open RMS protected PDF file, which is encrypted by on-premise/ADFS server.

**Comment by prvijay** [comment] 2015-08-20 04:42
Let's revisit after Aug 30th. @AgentRX

**Comment by AgentRX** [comment] 2015-09-01 08:07
Done by PR: https://github.com/AzureAD/rms-sdk-for-cpp/pull/91
@Kammy6679, now your have to provide IConsentCallback pointer (instead of link) that can be nullptr if you don't want to use it.

**Comment by Kammy6679** [comment] 2015-09-02 03:18
@AgentRX , We can't control that whether or not pass "NULL" to "IConsentCallback                 *consentCallback". In Mac, RMS SDK for Mac makes a judgment that whether to enter "virtual ConsentList Consents(ConsentList& consents) override", not the application to make a judgment.

**Comment by Kammy6679** [comment] 2015-09-06 07:57
@AgentRX ,  using the dev branch to verify this issue, we found that 
1. If decrypting the PPDF file, this issue has been fixed.
2. If decrypting the PDF file, we can reproduce this issue. The decryption process is: use "UserPolicy::Acquire" to create "std::shared_ptr<GetUserPolicyResult>", then use this "std::shared_ptr<GetUserPolicyResult>" to decrypt the PDF files.

**Comment by prvijay** [comment] 2015-09-09 16:50
@AgentRX - reactivating it based on Johnny's comment.

**Comment by AgentRX** [comment] 2015-09-09 17:06
@Kammy6679, please check the new version from PR: https://github.com/AzureAD/rms-sdk-for-cpp/pull/99

**Comment by Kammy6679** [comment] 2015-09-10 04:22
@AgentRX , do you merge this issue into master?

**Comment by prvijay** [comment] 2015-09-10 04:28
@Kammy6679 - just merged this into master. Can you please validate the fix and let us know if the issue is resolved. If not, please reactivate the same with the repro steps for us to take it fwd.

**Comment by Kammy6679** [comment] 2015-09-11 04:58
@prvijay , @AgentRX , we find that we can not enter the Consents callback function. How to enter the Consents callback function? 

In OS X, decrypting a PDF files(which is encrypted by another RMS server), will enter "virtual ConsentList Consents(ConsentList& consents) override;". For example: the current is a Online user login, then open RMS protected PDF file, which is encrypted by on-premise/ADFS server.

**Comment by prvijay** [comment] 2015-09-11 16:25
@Kammy6679 - what is the scenario impact by not fixing this issue in the way you have indicated. If the issue is not blocking a scenario, we should make progress.

**Comment by Kammy6679** [comment] 2015-09-14 10:14
@prvijay , 
In Windows/Mac/iOS/Android, Foxit Reader will pop up the following dialog box(I know other apps will also pop up this dialog, such Word):
https://cloud.githubusercontent.com/assets/10860444/9268033/3513b79a-428c-11e5-9051-6c45deadcbc3.jpg

NOTE: I think this is the SDK RMS specification.

**Comment by prvijay** [comment] 2015-09-14 14:37
@Kammy6679 - And what is happening in the Linux case? What was happening before the fix came in and what is happening now?

**Comment by AgentRX** [comment] 2015-09-14 15:14
@prvijay, @Kammy6679, we disabled content mechanism because it hasn't been implemented yet.
The RMS content callback is just linked with decryption BUT have to be linked with oAuth2 flows which could happens only in case of trusted AD FS servers (it should be checked).

Also I'm not sure Consent is a part of RMS API because RMS Auth library is managing oAuth2 authentications.

@Kammy6679, could you give an examples when Consent Callback is required and what is got as Consent Callback parameters? Do you need this mechanism and what for?

**Comment by prvijay** [comment] 2015-09-14 23:17
@Kammy6679, @AgentRX - if the issue is about showing the consent box - it's only shown in the on-prem RMS scenario. If the document is protected using Azure RMS, we redirect the users for authentication (to the cloud) without explicitly displaying the consent box. In which scenario are you observing the said behavior @Kammy6679 ?

**Comment by prvijay** [comment] 2015-09-15 16:32
Thanks @AgentRX, resolving the issue

**Closed as completed by prvijay** 2015-09-15 16:32 UTC
